version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - mv target/ROOT.war ROOT.war
artifacts:
  files:
    - ROOT.war